.TH "fixed_t" 3 "Version 1.0" "Fix" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fixed_t
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <FixLib\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBIntPart\fP"
.br
.ti -1c
.RI "int \fBFloatPart\fP"
.br
.ti -1c
.RI "char \fBIntLength\fP"
.br
.ti -1c
.RI "char \fBFloatLength\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBParameters\fP
.RS 4
\fIIntPart\fP Целочисленная часть числа 
.br
\fIFloatPart\fP Вещественная часть числа 
.br
\fIIntLength\fP Длина целочисленной части 
.br
\fIFloatLength\fP Длина вещественной части 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Fix from the source code\&.
